/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class LeaderboardUI extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardUI
     */
    public LeaderboardUI() {
        initComponents();
        ImageIcon img = new ImageIcon("D:\\JAVA OOP\\UASmk2\\src\\Assets\\ico.png");
        this.setIconImage(img.getImage());
        
        //Configuration for MainMenuUI :
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setBounds(300,100,800,630);
        this.setResizable(false);
        //END
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backLDBtn = new javax.swing.JButton();
        bgLD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Whack A Mole | 3A-PSTI");
        getContentPane().setLayout(null);

        backLDBtn.setBackground(new java.awt.Color(252, 215, 173));
        backLDBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/BackLDBtn.png"))); // NOI18N
        backLDBtn.setToolTipText("");
        backLDBtn.setBorder(null);
        backLDBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLDBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backLDBtn);
        backLDBtn.setBounds(60, 80, 100, 30);

        bgLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/LdUI.png"))); // NOI18N
        bgLD.setToolTipText("");
        getContentPane().add(bgLD);
        bgLD.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLDBtnActionPerformed
        // TODO add your handling code here:
        MainMenuUI me = new MainMenuUI();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLDBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLDBtn;
    private javax.swing.JLabel bgLD;
    // End of variables declaration//GEN-END:variables
}
