
package Game;

import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class MainMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI() {
        initComponents();
        ImageIcon img = new ImageIcon("src\\Assets\\ico.png");
        this.setIconImage(img.getImage());
        
        //Configuration for MainMenuUI :
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setBounds(300,100,800,630);
        this.setResizable(false);
        //END
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditsBtn = new javax.swing.JButton();
        leaderBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        backgroundMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Whack A Mole | 3A-PSTI");
        getContentPane().setLayout(null);

        creditsBtn.setBackground(new java.awt.Color(252, 215, 173));
        creditsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/credits-btn.png"))); // NOI18N
        creditsBtn.setBorder(null);
        creditsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(creditsBtn);
        creditsBtn.setBounds(520, 440, 205, 63);

        leaderBtn.setBackground(new java.awt.Color(252, 215, 173));
        leaderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lead-btn.png"))); // NOI18N
        leaderBtn.setBorder(null);
        leaderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(leaderBtn);
        leaderBtn.setBounds(520, 360, 205, 63);

        playBtn.setBackground(new java.awt.Color(252, 215, 173));
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/play-btn.png"))); // NOI18N
        playBtn.setBorder(null);
        playBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        getContentPane().add(playBtn);
        playBtn.setBounds(520, 280, 205, 63);

        backgroundMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/welcomeUI.png"))); // NOI18N
        getContentPane().add(backgroundMain);
        backgroundMain.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
        SelectUI sc = new SelectUI();
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playBtnActionPerformed

    private void leaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBtnActionPerformed
        // TODO add your handling code here:
        LeaderboardUI lead = new LeaderboardUI();
        lead.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaderBtnActionPerformed

    private void creditsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsBtnActionPerformed
        // TODO add your handling code here:
        TeamUI tm = new TeamUI();
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creditsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //START PROGRAM :
//        MainMenuUI mains = new MainMenuUI();
//        mains.setVisible(true);
//        mains.setLocationRelativeTo(null);
//        mains.setBounds(300,100,800,630);
//        mains.setResizable(false);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMain;
    private javax.swing.JButton creditsBtn;
    private javax.swing.JButton leaderBtn;
    private javax.swing.JButton playBtn;
    // End of variables declaration//GEN-END:variables
}
