/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class SelectUI extends javax.swing.JFrame {

    /**
     * Creates new form SelectUI
     */
    public SelectUI() {
        initComponents();
        ImageIcon img = new ImageIcon("D:\\JAVA OOP\\UASmk2\\src\\Assets\\ico.png");
        this.setIconImage(img.getImage());
        
        //Configuration for SelectUI :
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setBounds(300,100,800,630);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backDiffBtn = new javax.swing.JButton();
        hardBtn = new javax.swing.JButton();
        medBtn = new javax.swing.JButton();
        easyBtn = new javax.swing.JButton();
        bgDif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Whack A Mole | 3A-PSTI");
        getContentPane().setLayout(null);

        backDiffBtn.setBackground(new java.awt.Color(252, 215, 173));
        backDiffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/menu-back-dif.png"))); // NOI18N
        backDiffBtn.setBorder(null);
        backDiffBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backDiffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDiffBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backDiffBtn);
        backDiffBtn.setBounds(60, 80, 100, 30);

        hardBtn.setBackground(new java.awt.Color(252, 215, 173));
        hardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/hard-btn.png"))); // NOI18N
        hardBtn.setBorder(null);
        hardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hardBtn);
        hardBtn.setBounds(305, 390, 205, 63);

        medBtn.setBackground(new java.awt.Color(252, 215, 173));
        medBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/med-btn.png"))); // NOI18N
        medBtn.setBorder(null);
        medBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medBtnActionPerformed(evt);
            }
        });
        getContentPane().add(medBtn);
        medBtn.setBounds(305, 300, 205, 63);

        easyBtn.setBackground(new java.awt.Color(252, 215, 173));
        easyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/easy-btn.png"))); // NOI18N
        easyBtn.setBorder(null);
        easyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        easyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(easyBtn);
        easyBtn.setBounds(305, 217, 205, 63);

        bgDif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/DifficultyUI.png"))); // NOI18N
        getContentPane().add(bgDif);
        bgDif.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyBtnActionPerformed

    private void medBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medBtnActionPerformed

    private void hardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardBtnActionPerformed

    private void backDiffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDiffBtnActionPerformed
        // TODO add your handling code here:
        MainMenuUI mains = new MainMenuUI();
        mains.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backDiffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backDiffBtn;
    private javax.swing.JLabel bgDif;
    private javax.swing.JButton easyBtn;
    private javax.swing.JButton hardBtn;
    private javax.swing.JButton medBtn;
    // End of variables declaration//GEN-END:variables
}
